### ISSUE TITLE
Multisite database error.

### ISSUE THREAD

**Issue by Jeradin** [lesterchan/wp-useronline#13]
Hello there,

I was wondering if you plan to support multisite with this excellent plugin?

Obviously this might be a bit tricky with Multisites sharing the same user table, but would be a nice added feature!

Errors:
DELETE
FROM XXXXXXX_2_useronline
WHERE user_ip = '73.242.XXX.XX’
OR timestamp < DATE_SUB('2017-06-23 21:24:36', INTERVAL 300 SECOND)

SHOW FULL COLUMNS
FROM 'XXXXXXX_2_useronline'

SELECT COUNT( * )
FROM XXXXXXX_2_useronline

Thanks!

**Comment by lesterchan** [comment]
I have not tested it on MS as I don't use it myself. I didn't realize that MS users share the same wp_users table!
