### ISSUE TITLE
Function _load_textdomain_just_in_time was called incorrectly.

### ISSUE THREAD

**Issue by Martje65** [lesterchan/wp-useronline#62]
Sins WordPress 6.7 we have the next notice, please correct it.

Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the wp-useronline domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /wp-includes/functions.php on line 6114

**Comment by lesterchan** [comment]
Is this still not fixed in 2.88.4? https://github.com/lesterchan/wp-useronline/commit/ba95def75bda7db85c32782a2b6171e4a0a18ab6

**Comment by Martje65** [comment]
No, 
This is with V 2.88.4

**Comment by lesterchan** [comment]
Weird, the fix is what they recommended to add  `load_plugin_textdomain` during init. I am not sure what is the issue here now since there are no clear instructions from WP.

**Comment by Martje65** [comment]
With WordPress 6.7.1 there are still the same notice.

Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the wp-useronline domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /wp-includes/functions.php on line 6114

**Comment by lesterchan** [comment]
Hey @Martje65 might be an issue with the SCB, I have release 2.88.5, hopefully it fixes it

**Comment by Martje65** [comment]
That workt for me @lesterchan, thanks for the update.
