### ISSUE TITLE
[New Feature] Possible real time data update on the frontend? No page refresh

### ISSUE THREAD

**Issue by elvismdev** [lesterchan/wp-useronline#8]
Have you think implementing this at some moment?

Currently the number of users online shown on the frontend requires a page refresh to update that number. Will be good to come with an AngularJS like solution that could update that data for the frontend without page refresh while users comes in and out from the site.

That way others visitors who are stepped in at a page reading and article or watching a video can see the real time activity of online users on the site coming in and out.

**Comment by lesterchan** [comment]
The plugin already updates in real time every 5 mins. You can set the option in the settings. O
