### ISSUE TITLE
Invalid operand type - Expects Arrays

### ISSUE THREAD

**Issue by knoxcard** [lesterchan/wp-useronline#9]
Warning: Invalid operand type was used: get expects array(s) in /usr/local/nginx/html/wp-content/plugins/wp-useronline/scb/Options.php on line 62

**Comment by lesterchan** [comment]
How do you reproduce this?

**Comment by knoxcard** [comment]
From the command line with hhvm.
hhvm wp-config.php

**Comment by lesterchan** [comment]
I am using HHVM on my own site and it works fine.

**Comment by knoxcard** [comment]
have you tried running it from the command line or by web browser?

**Comment by lesterchan** [comment]
Huh? I have no idea what you are talking about. You are not suppose to run it on the command line. Are you sure you are even in the right place? It seems to me that you do not know what you are doing.

**Comment by knoxcard** [comment]
Did you not even read what I posted?  When you run it from the command line, it will display warnings. You do not see warnings from the web browser.  Running it from the command line shows you everything.

Earlier post.....
From the command line with hhvm.
hhvm wp-config.php

**Comment by lesterchan** [comment]
And why are you running ```hhvm wp-config.php```. You are not suppose to do that.

**Comment by knoxcard** [comment]
I am getting the same error for any file that I run it again.  That's why I posted wp-config.php.
I will figure out on my own, you already closed the ticket.

all i know is, i am getting this error..
wp-useronline/scb/Options.php

Also, I am running NGINX with HHVM, not Apache. That could very well be why this is happening.

**Comment by lesterchan** [comment]
I am also running HHVM with NGNIX

**Comment by knoxcard** [comment]
i created a fix, here is what worked for me.... 

	public function get( $field = null, $default = null ) {

		//echo gettype($this->defaults) . "\n";
		//echo gettype( get_option( $this->key, array() ) ). "\n";
		//echo gettype($this->key) . "\n";

		$option_array =  get_option( $this->key, array() );
		if(gettype($option_array) != "array") {
			$option_array = [];
		}
		$data = array_merge( $this->defaults, $option_array );

		return scbForms::get_value( $field, $data, $default );
	}

**Comment by knoxcard** [comment]
sometimes the get_option returns a boolean, not an array...which causes array_merge to throw a warning

**Comment by lesterchan** [comment]
Submit a pull request to the framework? https://github.com/scribu/wp-scb-framework

**Comment by knoxcard** [comment]
Pull request requested :+1:

**Comment by lesterchan** [comment]
Awesome thanks! Once scribu merged it, I will rebase on my end!
